/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef IMAGERESIZE_AUTODEFS_H
#define IMAGERESIZE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_IMAGERESIZE_NAME "imageResize"
#define S3E_EXT_IMAGERESIZE_HASH 0xf89dfb9a

#endif /* !IMAGERESIZE_AUTODEFS_H */
