/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "imageResize.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*imageResizeRegister_t)(imageResizeCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*imageResizeUnRegister_t)(imageResizeCallback cbid, s3eCallback fn);
typedef       bool(*resizeImage_t)(const char* src, const char* dest, int maxWidth, int maxHeight);
typedef       bool(*cnsSaveImageBufferToGallery_t)(const char* appname, int* buffer, int width, int height);

/**
 * struct that gets filled in by imageResizeRegister
 */
typedef struct imageResizeFuncs
{
    imageResizeRegister_t m_imageResizeRegister;
    imageResizeUnRegister_t m_imageResizeUnRegister;
    resizeImage_t m_resizeImage;
    cnsSaveImageBufferToGallery_t m_cnsSaveImageBufferToGallery;
} imageResizeFuncs;

static imageResizeFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xf89dfb9a, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: imageResize");
            
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xf89dfb9a, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool imageResizeAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult imageResizeRegister(imageResizeCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(IMAGERESIZE_VERBOSE, ("calling imageResize[0] func: imageResizeRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_imageResizeRegister(cbid, fn, userData);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult imageResizeUnRegister(imageResizeCallback cbid, s3eCallback fn)
{
    IwTrace(IMAGERESIZE_VERBOSE, ("calling imageResize[1] func: imageResizeUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_imageResizeUnRegister(cbid, fn);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool resizeImage(const char* src, const char* dest, int maxWidth, int maxHeight)
{
    IwTrace(IMAGERESIZE_VERBOSE, ("calling imageResize[2] func: resizeImage"));

    if (!_extLoad())
        return false;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_resizeImage(src, dest, maxWidth, maxHeight);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool cnsSaveImageBufferToGallery(const char* appname, int* buffer, int width, int height)
{
    IwTrace(IMAGERESIZE_VERBOSE, ("calling imageResize[3] func: cnsSaveImageBufferToGallery"));

    if (!_extLoad())
        return false;

#ifdef __mips
    // For MIPs platform we do not have asm code for stack switching 
    // implemented. So we make LoaderCallStart call manually to set GlobalLock
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_cnsSaveImageBufferToGallery(appname, buffer, width, height);

#ifdef __mips
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}
