/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "imageResize.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       bool(*resizeImage_t)(const char* src, const char* dest, int maxWidth, int maxHeight);

/**
 * struct that gets filled in by imageResizeRegister
 */
typedef struct imageResizeFuncs
{
    resizeImage_t m_resizeImage;
} imageResizeFuncs;

static imageResizeFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xf89dfb9a, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: imageResize");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xf89dfb9a, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool imageResizeAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

bool resizeImage(const char* src, const char* dest, int maxWidth, int maxHeight)
{
    IwTrace(IMAGERESIZE_VERBOSE, ("calling imageResize[0] func: resizeImage"));

    if (!_extLoad())
        return false;

    return g_Ext.m_resizeImage(src, dest, maxWidth, maxHeight);
}
